apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        type: choice
        options:
          - dev
          - staging
          - prod
        required: true
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
      - name: hi
        run: pip install -r requirements.txt
        uses: docker://python:3.12-slim
        shell: sh
